# For more information: https://laravel.com/docs/sail
version: '3'

services:
    laravel.test:
        image: ghcr.io/mikebronner/sail/php-8.2:latest
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail

networks:
    sail:
        driver: bridge

volumes:
    sail-meilisearch:
        driver: local
    sail-minio:
        driver: local
    sail-pgsql:
        driver: local
    sail-redis:
        driver: local
